name = "DimiPack Forge 1.18.2"
author = "DimiDimit"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "712d751e81e9ef7a185bb0d04bdf68a414f80f402a14aad46f21d2e0f0a3e42b"

[versions]
forge = "40.0.0"
minecraft = "1.18.2"
