name = "DimiPack Forge 1.18.2"
author = "DimiDimit"
version = "0.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a94a1bd972d2c8098fe0c54d53403bc59cce1fe3467bb591e3ce550bd04636c2"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
