name = "DimiPack Forge 1.18.2"
author = "DimiDimit"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c12c3315f146816a3246676536c66ff5991549f34e8c975d103f88ebaad064be"

[versions]
forge = "40.1.68"
minecraft = "1.18.2"
